## Rolling Stone top 500 albums analysis

This is project about top 500 albums of all time from based on the Rolling Stone magazine. First we re gonna import the pandas module:

In [1]:
import pandas as pd

And store the data set to the pandas Data Frame

In [ ]:
file = open('albumlist.csv')
df = pd.read_csv(file, index_col=0)

Now we re gonna see how many rows and columns our set have

In [ ]:
df.shape

(500, 5)

It contains 500 rows and 5 columns

Name and the describe of the column

|name|description|
|:----:|:----:|
|Position on the list|album index in the list|
|Year|Year of release|
|Album|album name|
|Artist|name of the artist or artists|
|Genre|Name of the genre for example rock, pop, jazz, blues|
|Subgenre|Subgenre name - like folk rock, psychodelic rock|

Here we gonna see the data types of the table columns

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 1 to 500
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Year      500 non-null    int64
 1   Album     500 non-null    object
 2   Artist    500 non-null    object
 3   Genre     500 non-null    object
 4   Subgenre  500 non-null    object
dtypes: int64(1), object(4)
memory usage: 23.4+ KB

In [ ]:
df[df["Artist"] == "Bob Dylan"]

,Year,Album,Artist,Genre,Subgenre
Number,,,,,
4,1965,Highway 61 Revisited,Bob Dylan,Rock,"Folk Rock, Blues Rock"
9,1966,Blonde on Blonde,Bob Dylan,"Rock, Blues","Folk Rock, Rhythm & Blues"
16,1975,Blood on the Tracks,Bob Dylan,Rock,"Folk Rock, Acoustic, Ballad"
31,1965,Bringing It All Back Home,Bob Dylan,"Rock, Folk, World, & Country","Folk Rock, Folk"
97,1963,The Freewheelin' Bob Dylan,Bob Dylan,"Folk, World, & Country",Folk
174,1976,Desire,Bob Dylan,Rock,Folk Rock
204,2006,Modern Times,Bob Dylan,Rock,"Blues Rock, Folk Rock"
303,1967,John Wesley Harding,Bob Dylan,Rock,"Folk Rock, Country Rock"
385,2001,"""Love and Theft""",Bob Dylan,Rock,"Folk Rock, Blues Rock"
410,1997,Time Out of Mind,Bob Dylan,"Rock, Blues",Blues Rock

According to the numpy we can do it also like this but the example above is way much cleaner

In [ ]:
df.loc[:,'Genre']

Number
1           Rock
2           Rock
3           Rock
4           Rock
5      Rock, Pop
         ...
496         Rock
497         Rock
498         Rock
499        Blues
500      Hip Hop
Name: Genre, Length: 500, dtype: object

When we wanna select the multiple columns:

In [ ]:
df[["Genre", "Artist"]]

            Genre             Artist
Number
1            Rock        The Beatles
2            Rock     The Beach Boys
3            Rock        The Beatles
4            Rock          Bob Dylan
5       Rock, Pop        The Beatles
...           ...                ...
496          Rock         Boz Scaggs
497          Rock  The White Stripes
498          Rock    The Stone Roses
499         Blues          B.B. King
500       Hip Hop            OutKast

[500 rows x 2 columns]

Numpy explanation again

In [ ]:
df.loc[:,["Genre", "Artist"]]

            Genre             Artist
Number
1            Rock        The Beatles
2            Rock     The Beach Boys
3            Rock        The Beatles
4            Rock          Bob Dylan
5       Rock, Pop        The Beatles
...           ...                ...
496          Rock         Boz Scaggs
497          Rock  The White Stripes
498          Rock    The Stone Roses
499         Blues          B.B. King
500       Hip Hop            OutKast

[500 rows x 2 columns]

When we re slicing something peculliar gonna happen

In [ ]:
df.loc[:,"Artist": "Subgenre"]

,Artist,Genre,Subgenre
Number,,,
1,The Beatles,Rock,"Rock & Roll, Psychedelic Rock"
2,The Beach Boys,Rock,"Pop Rock, Psychedelic Rock"
3,The Beatles,Rock,"Psychedelic Rock, Pop Rock"
4,Bob Dylan,Rock,"Folk Rock, Blues Rock"
5,The Beatles,"Rock, Pop",Pop Rock
...,...,...,...
496,Boz Scaggs,Rock,Pop Rock
497,The White Stripes,Rock,"Indie Rock, Alternative Rock, Blues Rock, Gara..."
498,The Stone Roses,Rock,Indie Rock
499,B.B. King,Blues,Electric Blues
500,OutKast,Hip Hop,"Reggae, Gangsta, Soul, Conscious"

last column gonna be included to the slice

Now when we leaarned how to select column by the label, let's learn how to select rows

In [ ]:
df.loc[3] #  It's the way how we selecting the whole row

Year                              1966
Album                         Revolver
Artist                     The Beatles
Genre                             Rock
Subgenre    Psychedelic Rock, Pop Rock
Name: 3, dtype: object

And multiple rows:

In [ ]:
df.loc[[1,5,499]]

,Year,Album,Artist,Genre,Subgenre
Number,,,,,
1,1967,Sgt. Pepper's Lonely Hearts Club Band,The Beatles,Rock,"Rock & Roll, Psychedelic Rock"
5,1965,Rubber Soul,The Beatles,"Rock, Pop",Pop Rock
499,1971,Live in Cook County Jail,B.B. King,Blues,Electric Blues

Selecting slice:

In [ ]:
s = df.loc[1:40]

Again the 40th row is included

In [ ]:
s

,Year,Album,Artist,Genre,Subgenre
Number,,,,,
1,1967,Sgt. Pepper's Lonely Hearts Club Band,The Beatles,Rock,"Rock & Roll, Psychedelic Rock"
2,1966,Pet Sounds,The Beach Boys,Rock,"Pop Rock, Psychedelic Rock"
3,1966,Revolver,The Beatles,Rock,"Psychedelic Rock, Pop Rock"
4,1965,Highway 61 Revisited,Bob Dylan,Rock,"Folk Rock, Blues Rock"
5,1965,Rubber Soul,The Beatles,"Rock, Pop",Pop Rock
6,1971,What's Going On,Marvin Gaye,Funk / Soul,Soul
7,1972,Exile on Main St.,The Rolling Stones,Rock,"Blues Rock, Rock & Roll, Classic Rock"
8,1979,London Calling,The Clash,Rock,"Punk, New Wave"
9,1966,Blonde on Blonde,Bob Dylan,"Rock, Blues","Folk Rock, Rhythm & Blues"
10,1968,"The Beatles (""The White Album"")",The Beatles,Rock,"Rock & Roll, Pop Rock, Psychedelic Rock, Exper..."
11,1976,The Sun Sessions,Elvis Presley,Rock,Rock & Roll
12,1959,Kind of Blue,Miles Davis,Jazz,Modal
13,1967,The Velvet Underground & Nico,The Velvet Underground,Rock,"Garage Rock, Art Rock, Experimental"
14,1969,Abbey Road,The Beatles,Rock,"Psychedelic Rock, Classic Rock, Pop Rock"
15,1967,Are You Experienced,The Jimi Hendrix Experience,"Rock, Blues","Blues Rock, Psychedelic Rock"
16,1975,Blood on the Tracks,Bob Dylan,Rock,"Folk Rock, Acoustic, Ballad"
17,1991,Nevermind,Nirvana,Rock,"Alternative Rock, Grunge"
18,1975,Born to Run,Bruce Springsteen,Rock,Pop Rock
19,1968,Astral Weeks,Van Morrison,"Jazz, Rock, Blues, Folk, World, & Country","Acoustic, Classic Rock, Free Improvisation"
20,1982,Thriller,Michael Jackson,"Funk / Soul, Pop",Disco
21,1982,The Great Twenty_Eight,Chuck Berry,Rock,Rock & Roll
22,1990,The Complete Recordings,Robert Johnson,Blues,Delta Blues
23,1970,John Lennon/Plastic Ono Band,John Lennon / Plastic Ono Band,Rock,Pop Rock
24,1973,Innervisions,Stevie Wonder,Funk / Soul,Soul
25,1963,"Live at the Apollo, 1962",James Brown,Funk / Soul,"Rhythm & Blues, Soul"
26,1977,Rumours,Fleetwood Mac,Rock,Pop Rock
27,1987,The Joshua Tree,U2,Rock,"Alternative Rock, Pop Rock"
28,1971,Who's Next,The Who,Rock,"Hard Rock, Mod, Prog Rock, Psychedelic Rock"
29,1969,Led Zeppelin,Led Zeppelin,Rock,"Blues Rock, Hard Rock"
30,1971,Blue,Joni Mitchell,Pop,"Acoustic, Ballad, Folk"
31,1965,Bringing It All Back Home,Bob Dylan,"Rock, Folk, World, & Country","Folk Rock, Folk"
32,1969,Let It Bleed,The Rolling Stones,Rock,"Blues Rock, Hard Rock"
33,1976,Ramones,Ramones,Rock,"Rock & Roll, Punk"
34,1968,Music From Big Pink,The Band,Rock,"Folk Rock, Acoustic, Blues Rock"
35,1972,The Rise and Fall of Ziggy Stardust and the Sp...,David Bowie,Rock,"Classic Rock, Glam"
36,1971,Tapestry,Carole King,"Rock, Pop","Folk Rock, Soft Rock"
37,1976,Hotel California,Eagles,Rock,Classic Rock
38,2001,The Anthology,Muddy Waters,"Folk, World, & Country",Folk
39,1963,Please Please Me,The Beatles,Rock,"Beat, Rock & Roll"
40,1967,Forever Changes,Love,Rock,"Folk Rock, Psychedelic Rock"

The type is data frame

In [ ]:
type(s)

pandas.core.frame.DataFrame

Because series and dataframes are two distinct objects, they have their own unique methods

In [ ]:
artists = df["Artist"]

artists_value_counts = artists.value_counts()
artists_value_counts[:10]

The Beatles           10
The Rolling Stones    10
Bob Dylan             10
Bruce Springsteen      8
The Who                7
David Bowie            5
Led Zeppelin           5
Various Artists        5
Radiohead              5
U2                     5
Name: Artist, dtype: int64

In the resulting series, we can see each unique non-null value in the column and their counts.

When we wanna see for examply only count of Bob Dylan's Albums:

In [ ]:
artists_value_counts["Bob Dylan"]

10

For example we wanna have also the Bawid Bowie and the Beatles album's count:

In [ ]:
artists_value_counts[["The Beatles", "David Bowie", "Bob Dylan"]]

The Beatles    10
David Bowie     5
Bob Dylan      10
Name: Artist, dtype: int64

Now I' m gonna select the newest album(s) on this list

In [ ]:
df["Year"].max()

2011

In [ ]:
df[df["Year"] == 2011]

,Year,Album,Artist,Genre,Subgenre
Number,,,,,
381,2011,The Smile Sessions,The Beach Boys,Rock,"Pop Rock, Psychedelic Rock"

This album is just released in this year, but it was recorded in 1966-1967, so I m gonna look also for 2010

In [ ]:
df[df["Year"] == 2010]

        Year                              Album      Artist    Genre Subgenre
Number
353     2010  My Beautiful Dark Twisted Fantasy  Kanye West  Hip Hop     None

Here we have "My Beautiful Dark Twisted Fantasy" by Kayne West

Lets see the oldest one

In [ ]:
min_year = df["Year"].min()

In [ ]:
df[df["Year"] == min_year]

,Year,Album,Artist,Genre,Subgenre
Number,,,,,
101,1955,In the Wee Small Hours,Frank Sinatra,"Jazz, Pop","Big Band, Ballad"

Here we have "In the Wee Small Hours" by Frank Sinatra

I'm also interested in the frequency table in this schema Genre:albums amount so:

In [ ]:
genres = df['Genre']

artists_value_counts = genres.value_counts()
artists_value_counts[:20]

Rock                            249
Funk / Soul                      38
Hip Hop                          29
Electronic, Rock                 19
Rock, Pop                        18
Rock, Blues                      16
Folk, World, & Country           13
Rock, Folk, World, & Country      9
Blues                             8
Jazz                              7
Electronic                        7
Funk / Soul, Pop                  6
Reggae                            6
Electronic, Pop                   5
Rock, Funk / Soul                 5
Funk / Soul, Blues                4
Hip Hop, Funk / Soul              3
Jazz, Pop                         3
Rock, Funk / Soul, Pop            3
Rock, Stage & Screen              3
Name: Genre, dtype: int64

We can see that almost half is of all 500 albums is pure rock genre

In [ ]:
genres = df['Year']

artists_value_counts = genres.value_counts()

In [ ]:
df["Genre"].describe()

count      500
unique      63
top       Rock
freq       249
Name: Genre, dtype: object

Using the **method chainng** to achieve how many jazz albums are on the rolling stone list

In [ ]:
df["Genre"].value_counts().loc["Jazz"]

7

Using the method chaining to calculate the median year of each album

In [ ]:
df['Year'].median(axis=0) #  we can also use axis = "index" as a parameter
#  defualt value for axis parameter is 0 so we even dont need to assign it

1976.0

Using the describe method to look at the values

In [ ]:
df.describe(include = ['O'])

                Album       Artist Genre Subgenre
count             500          500   500      500
unique            497          289    63      290
top     Greatest Hits  The Beatles  Rock     None
freq                3           10   249       29

By default its gonna take the numeric values

In [ ]:
df.describe()

              Year
count   500.000000
mean   1979.270000
std      12.093701
min    1955.000000
25%    1970.000000
50%    1976.000000
75%    1988.000000
max    2011.000000

In [ ]:
df

,Year,Album,Artist,Genre,Subgenre
Number,,,,,
1,1967,Sgt. Pepper's Lonely Hearts Club Band,The Beatles,Rock,"Rock & Roll, Psychedelic Rock"
2,1966,Pet Sounds,The Beach Boys,Rock,"Pop Rock, Psychedelic Rock"
3,1966,Revolver,The Beatles,Rock,"Psychedelic Rock, Pop Rock"
4,1965,Highway 61 Revisited,Bob Dylan,Rock,"Folk Rock, Blues Rock"
5,1965,Rubber Soul,The Beatles,"Rock, Pop",Pop Rock
...,...,...,...,...,...
496,1969,Boz Scaggs,Boz Scaggs,Rock,Pop Rock
497,2001,White Blood Cells,The White Stripes,Rock,"Indie Rock, Alternative Rock, Blues Rock, Gara..."
498,1989,The Stone Roses,The Stone Roses,Rock,Indie Rock
499,1971,Live in Cook County Jail,B.B. King,Blues,Electric Blues
500,1998,Aquemini,OutKast,Hip Hop,"Reggae, Gangsta, Soul, Conscious"

When we wanna find the particular column using the index and selecting the column:

In [ ]:
df.loc[145,"Genre"]

'Jazz, Rock'

Or the columns

In [ ]:
df.loc[145, ["Genre", "Artist"]]

Genre     Jazz, Rock
Artist    Steely Dan
Name: 145, dtype: object

NameError: ignored